# Generated by Django 3.2.6 on 2021-10-28 00:11

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_auto_20211025_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipo de documentos',
            },
        ),
        migrations.CreateModel(
            name='DocuEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=50, verbose_name='nombre del documento')),
                ('path_documento', models.FileField(blank=True, null=True, upload_to=documentos.models.subir_documentos)),
                ('subido_el', models.DateField(auto_now_add=True, verbose_name='Subido el')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Nombre documento',
                'verbose_name_plural': 'Nombre documentos',
            },
        ),
        migrations.CreateModel(
            name='DocuEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=50, verbose_name='nombre del documento')),
                ('path_documento', models.FileField(blank=True, null=True, upload_to=documentos.models.subir_documentos)),
                ('subido_el', models.DateField(auto_now_add=True, verbose_name='Subido el')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
            ],
            options={
                'verbose_name': 'Nombre documento empleado',
                'verbose_name_plural': 'Nombre documentos empleados',
            },
        ),
    ]
