# Generated by Django 3.2.7 on 2021-11-27 21:10

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '__first__'),
        ('comites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipo de documentos',
            },
        ),
        migrations.CreateModel(
            name='DocuEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=50, verbose_name='nombre del documento')),
                ('path_documento', models.FileField(blank=True, null=True, upload_to=documentos.models.subir_documentos, verbose_name='Archivo')),
                ('subido_el', models.DateField(auto_now_add=True, verbose_name='Subido el')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('tipo_documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento empresa',
                'verbose_name_plural': 'Documentos empresa',
            },
        ),
        migrations.CreateModel(
            name='DocuEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=50, verbose_name='nombre del documento')),
                ('path_documento', models.FileField(blank=True, null=True, upload_to=documentos.models.subir_docuEmpleados, verbose_name='Archivo')),
                ('subido_el', models.DateField(auto_now_add=True, verbose_name='Subido el')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
                ('tipo_documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento empleado',
                'verbose_name_plural': 'Documentos empleados',
            },
        ),
        migrations.CreateModel(
            name='DocsComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=50, verbose_name='nombre del documento')),
                ('path_documento', models.FileField(blank=True, null=True, upload_to=documentos.models.subir_docscomite, verbose_name='Archivo')),
                ('subido_el', models.DateField(auto_now_add=True, verbose_name='Subido el')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comites.comites')),
                ('tipo_documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento comite',
                'verbose_name_plural': 'Documentos comites',
            },
        ),
    ]
