# Generated by Django 3.2.7 on 2021-11-04 00:16

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('comites', '0001_initial'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuempleados',
            name='path_documento',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.subir_docuEmpleados),
        ),
        migrations.CreateModel(
            name='DocsComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=50, verbose_name='nombre del documento')),
                ('path_documento', models.FileField(blank=True, null=True, upload_to=documentos.models.subir_docscomite)),
                ('subido_el', models.DateField(auto_now_add=True, verbose_name='Subido el')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comites.comites')),
            ],
            options={
                'verbose_name': 'Nombre documento comite',
                'verbose_name_plural': 'Nombre documentos comites',
            },
        ),
    ]
