# Generated by Django 3.2.7 on 2021-11-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20211103_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docscomite',
            options={'verbose_name': 'Documento comite', 'verbose_name_plural': 'Documentos comites'},
        ),
        migrations.AlterModelOptions(
            name='docuempleados',
            options={'verbose_name': 'Documento empleado', 'verbose_name_plural': 'Documentos empleados'},
        ),
        migrations.AlterModelOptions(
            name='docuempresa',
            options={'verbose_name': 'Documento Empresa', 'verbose_name_plural': 'Documentos Empresas'},
        ),
    ]
