# Generated by Django 3.2.6 on 2021-11-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20211110_1416'),
        ('documentos', '0004_auto_20211112_1826'),
    ]

    operations = [
    ]
