# Generated by Django 3.2.6 on 2021-11-13 15:29

from django.db import migrations, models
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_merge_0003_auto_20211110_1416_0004_auto_20211112_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docscomite',
            name='path_documento',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.subir_docscomite, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='docuempleados',
            name='path_documento',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.subir_docuEmpleados, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='docuempresa',
            name='path_documento',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.subir_documentos, verbose_name='Archivo'),
        ),
    ]
