# Generated by Django 3.2.6 on 2021-11-18 01:44

from django.db import migrations, models
import django.db.models.deletion
import formatos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0005_auto_20211117_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuejasAcosoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diligenciamiento', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hechos', models.TextField(verbose_name='Descripción de los hechos')),
                ('pruebas', models.TextField(verbose_name='Descripción de pruebas')),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to=formatos.models.adjuntos_quejas)),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
            ],
            options={
                'verbose_name': 'Queja de acoso laboral',
                'verbose_name_plural': 'Quejas de acoso laboral',
            },
        ),
    ]
