# Generated by Django 3.2.7 on 2021-11-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleelementos',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='detalleelementos',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='elementos',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='teléfono1',
            new_name='telefono1',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='teléfono2',
            new_name='telefono2',
        ),
    ]
