# Generated by Django 3.2.7 on 2021-11-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20211105_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='activo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Se encuentra activo?'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='es_autorizado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Se encuentra autorizado?'),
        ),
    ]
