# Generated by Django 3.2.7 on 2021-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20211110_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementos',
            name='activo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Se encuentra activo?'),
        ),
    ]
