# Generated by Django 3.2.7 on 2021-11-20 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=150, verbose_name='Área')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('salario_cargo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario del cargo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(max_length=40, verbose_name='Nivel Acedémico')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Nivel académico',
                'verbose_name_plural': 'Niveles académicos',
            },
        ),
        migrations.CreateModel(
            name='Sanidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=255, verbose_name='Nombre de la enfermedad')),
                ('pandemia', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Es Pandemia?')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Sanidad (COVID-19 u otras)',
                'verbose_name_plural': 'Sanidad (COVID-19 u otras)',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=150, verbose_name='Tipo de empresa')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Tipo de empresa',
                'verbose_name_plural': 'Tipo de empresa',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre de la empresa')),
                ('nit', models.CharField(max_length=25, verbose_name='Número de identificación tributaria')),
                ('actividad_economica', models.CharField(max_length=50, verbose_name='Actividad económica')),
                ('nivel_de_riesgo', models.CharField(max_length=10, verbose_name='Nivel de riesgo')),
                ('naturaleza_juridica', models.CharField(max_length=50, verbose_name='Naturaleza jurídica')),
                ('correo_electronico', models.CharField(max_length=25, verbose_name='Correo electrónico')),
                ('tipo_de_empresa', models.CharField(max_length=25, verbose_name='Tipo de empresa')),
                ('numeros_telefonicos', models.CharField(max_length=40, verbose_name='Números telefónicos')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('tipo_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.tipoempresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=30, null=True, verbose_name='ID empleado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo')),
                ('eps', models.CharField(default='N/A', max_length=100, verbose_name='EPS')),
                ('arl', models.CharField(default='N/A', max_length=100, verbose_name='ARL')),
                ('afp', models.CharField(default='N/A', max_length=100, verbose_name='AFP')),
                ('cuenta_bancaria', models.CharField(max_length=30, null=True, verbose_name='Número de cuenta bancaria')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.areas')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargos')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.nivelacademico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='DetalleSanidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=144, verbose_name='Vacuna')),
                ('dosis', models.IntegerField(blank=True, null=True, verbose_name='Número de dosis')),
                ('fecha_dosis', models.DateField(verbose_name='Fecha de aplicación')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sanidad')),
            ],
            options={
                'verbose_name': 'Sanidad - Detalle tratamiento',
                'verbose_name_plural': 'Sanidad - Detalle tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capacitacion', models.CharField(max_length=400, verbose_name='Nombre de la capacitación')),
                ('certificado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Tiene certificado?')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
