# Generated by Django 3.2.6 on 2021-10-26 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('salario_cargo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario del cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(max_length=40, verbose_name='Nivel Acedémico')),
            ],
            options={
                'verbose_name': 'Nivel académico',
                'verbose_name_plural': 'Niveles académicos',
            },
        ),
        migrations.AlterField(
            model_name='areas',
            name='nombre_area',
            field=models.CharField(max_length=150, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargos'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.nivelacademico'),
        ),
    ]
