# Generated by Django 3.2.6 on 2021-11-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211025_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=255, verbose_name='Tipo de Enfermedad')),
                ('pandemia', models.CharField(max_length=2, verbose_name='Es Pandemia?')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Sanidad (COVID-19 u otras)',
                'verbose_name_plural': 'Sanidades (COVID-19 u otras)',
            },
        ),
        migrations.CreateModel(
            name='DetalleSanidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=144, verbose_name='Vacuna')),
                ('dosis', models.IntegerField(blank=True, null=True, verbose_name='Número de dosis')),
                ('fecha_dosis', models.DateField(verbose_name='Fecha de aplicación')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sanidad')),
            ],
            options={
                'verbose_name': 'Detalle tratamiento',
                'verbose_name_plural': 'Detalle tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capacitacion', models.CharField(max_length=400, verbose_name='Nombre de la capacitación')),
                ('certificado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Tiene certificado?')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
            ],
        ),
    ]
