# Generated by Django 3.2.6 on 2021-11-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20211113_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='afp',
            field=models.CharField(default='N/A', max_length=100, verbose_name='AFP'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='arl',
            field=models.CharField(default='N/A', max_length=100, verbose_name='ARL'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='eps',
            field=models.CharField(default='N/A', max_length=100, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='sanidad',
            name='enfermedad',
            field=models.CharField(max_length=255, verbose_name='Nombre de la enfermedad'),
        ),
        migrations.AlterField(
            model_name='sanidad',
            name='pandemia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Es Pandemia?'),
        ),
    ]
