# Generated by Django 3.2.7 on 2021-11-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '__first__'),
        ('proveedores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.TextField(max_length=100, verbose_name='Actividad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('responsable', models.CharField(max_length=250, verbose_name='Responsable')),
                ('valor_presupuestado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Presupuestado')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleados')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=4, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='EjecucionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('numero_factura', models.CharField(max_length=20, verbose_name='Número de factura')),
                ('cantidad', models.CharField(max_length=250, verbose_name='cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Unitario')),
                ('valor_iva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor IVA')),
                ('total_unidades', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Unidades')),
                ('total_ejecucion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Ejecución')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronograma.cronogramapresupuesto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Ejecución',
            },
        ),
        migrations.AddField(
            model_name='cronogramapresupuesto',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cronograma.periodo'),
        ),
    ]
