# Generated by Django 3.2.7 on 2021-11-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenazaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_amenaza', models.CharField(max_length=350, verbose_name='Nombre de la amenaza')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Nombre de la amenaza',
                'verbose_name_plural': 'Nombre de las amenazas',
            },
        ),
        migrations.CreateModel(
            name='CausaAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_causa_amenaza', models.CharField(max_length=350, verbose_name='Nombre de la causa de la amenaza')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('amenaza_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.amenazariesgo')),
            ],
            options={
                'verbose_name': 'Nombre de la causa de la amenaza',
                'verbose_name_plural': 'Nombre de la causas de las amenazas',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de la Evaluación')),
                ('nombre_evaluacion', models.CharField(max_length=350, verbose_name='Nombre de la evaluación')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Nombre de la evaluación',
                'verbose_name_plural': 'Nombre de las evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='OrigenAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_origen_amenaza', models.CharField(max_length=350, verbose_name='Nombre del origen de la amenaza')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Nombre del origen de la amenaza',
                'verbose_name_plural': 'Nombre del origen de las amenazas',
            },
        ),
        migrations.CreateModel(
            name='TipoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_riesgo', models.CharField(max_length=350, verbose_name='Tipo de riesgo')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Tipo de riesgo',
                'verbose_name_plural': 'Tipos de riesgos',
            },
        ),
        migrations.CreateModel(
            name='DetalleAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles_amenaza', models.CharField(max_length=350, verbose_name='Detalle de la amenaza')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.areas')),
                ('causa_amenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.causaamenaza')),
                ('origen_amenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.origenamenaza')),
            ],
            options={
                'verbose_name': 'Detalle de la amenaza',
                'verbose_name_plural': 'Detalle de las amenazas',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionesRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificaciones_riesgos', models.CharField(max_length=350, verbose_name='clasificaciones de los riesgos')),
                ('resultados', models.CharField(max_length=50, verbose_name='resultado')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('amenaza_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.amenazariesgo')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.evaluacion')),
            ],
            options={
                'verbose_name': 'clasificacion del riesgo',
                'verbose_name_plural': 'clasificaciones de los riesgos',
            },
        ),
        migrations.AddField(
            model_name='amenazariesgo',
            name='tipo_riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.tiporiesgo'),
        ),
    ]
