# Generated by Django 3.2.7 on 2021-11-23 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pqrs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quejas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queja', models.TextField(verbose_name='Queja')),
                ('evidencia', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='¿Cuenta con evidencia?')),
                ('soporte', models.FileField(null=True, upload_to=pqrs.models.subir_evidencia)),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Registrado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PQRS Acoso laboral',
                'verbose_name_plural': 'PQRS Acoso laboral',
            },
        ),
        migrations.CreateModel(
            name='AccionesQueja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_accion', models.TextField(verbose_name='Acciones sobre la queja')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Registrado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.quejas')),
            ],
            options={
                'verbose_name': 'Atenciones',
                'verbose_name_plural': 'Atenciones',
            },
        ),
    ]
