# Generated by Django 3.2.7 on 2021-10-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modify_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
