# Generated by Django 3.2.6 on 2021-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_profile_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modify_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Género'),
        ),
    ]
