# Generated by Django 3.2.7 on 2021-11-17 23:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_contacto_emergencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto_Emergencia',
            new_name='ContactoEmergencia',
        ),
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='parentesco_emergercia',
            new_name='parentesco_emergencia',
        ),
    ]
