# Generated by Django 3.2.7 on 2021-11-20 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronograma', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_PHVA', models.CharField(choices=[('Planear', 'Planear'), ('Hacer', 'Hacer'), ('Verificar', 'Verificar'), ('Actuar', 'Actuar')], max_length=25, verbose_name='Etapa PHVA')),
                ('actividad', models.TextField(max_length=500, verbose_name='Actividad')),
                ('recursos', models.TextField(max_length=60, verbose_name='Recursos')),
                ('periocidad', models.CharField(max_length=50, verbose_name='Periocidad')),
                ('fecha_planeacion', models.DateField(null=True, verbose_name='Fecha de Planeación')),
                ('estado_actividad', models.CharField(max_length=30, verbose_name='Estado de la Actividad')),
                ('nombre_archivo', models.CharField(max_length=10, verbose_name='Nombre del archivo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name_plural': 'Plan de Actividades',
            },
        ),
        migrations.CreateModel(
            name='EstructuraSGSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Estructura SGSST',
                'verbose_name_plural': 'Estructuras SGSST',
            },
        ),
        migrations.CreateModel(
            name='PlanAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField(max_length=250, verbose_name='Objetivo')),
                ('metas', models.TextField(max_length=500, verbose_name='Metas')),
                ('alcance', models.TextField(max_length=250, verbose_name='Alcance')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronograma.periodo')),
            ],
            options={
                'verbose_name': 'Plan Anual',
            },
        ),
        migrations.CreateModel(
            name='CumplimientoActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cumplimiento', models.DateField(null=True, verbose_name='Fecha de Cumplimiento')),
                ('nombre_archivo', models.CharField(max_length=60, verbose_name='Evidencia')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planAnual.actividadesplan')),
            ],
            options={
                'verbose_name': 'Cumplimiento de la actividad',
                'verbose_name_plural': 'Cumplimiento de las actividades',
            },
        ),
        migrations.AddField(
            model_name='actividadesplan',
            name='id_estructura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planAnual.estructurasgsst'),
        ),
        migrations.AddField(
            model_name='actividadesplan',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planAnual.plananual'),
        ),
        migrations.AddField(
            model_name='actividadesplan',
            name='id_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.areas'),
        ),
    ]
