# Generated by Django 3.2.6 on 2021-11-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planAnual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plananual',
            name='nombre_archivo',
        ),
    ]
