# Generated by Django 3.2.7 on 2021-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planAnual', '0002_remove_plananual_nombre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plananual',
            name='nombre_archivo',
            field=models.CharField(blank=True, default=1, max_length=60, null=True, verbose_name='Objetivos'),
        ),
    ]
