# Generated by Django 3.2.7 on 2021-11-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantecomite',
            name='participantes_comite',
        ),
        migrations.AlterField(
            model_name='participantecomite',
            name='rol_comite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comites.rolcomite'),
        ),
    ]
